services:

# PostgreSQL service configuration
  postgres:
    image: postgres:15-alpine
    container_name: test_postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

# 
volumes:
  postgres_data:

networks:
  app_network:
    